services:
  mongodb:
    # image: mongo:7.0.3
    image: mongo:4.4.25
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  
  mongo-express:
    image: mongo-express:1.0.0-18
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_BASICAUTH_USERNAME: aller
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb-network
